name: Publish to PyPI

on:
  release:
    types: [published]

  workflow_dispatch:
jobs:
  build:
    name: Build and publish Python distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize Python 3.9
      uses: actions/setup-python@v1
      with:
          python-version: 3.9

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip

    - name: Build binary wheel and a source tarball
      run: python setup.py sdist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
